env:
  browser: true
  es6: true
extends:
    - google
    - "plugin:@typescript-eslint/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: "./tsconfig.json"
rules: {}
parser:
    "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
